### ISSUE TITLE
Automate the norovirus pathogen repository

### ISSUE THREAD

**Issue by j23414** [nextstrain/norovirus#4]
### Context

During Nextstrain office hours and DM's, there has been expressed interest in an automated norovirus pathogen pipeline.

### Tasks

* [ ] Add `ingest` workflow https://github.com/nextstrain/norovirus/issues/1
* [ ] Refactor existing rules into `phylogenetic` workflow
* [ ] Add `nextclade` workflow https://github.com/nextstrain/norovirus/issues/2
  * [ ] temporary bypass this requirement by using the joining existing GenomeDetective results
* [ ] Add automation and push draft page to the staging site
* [ ] Collect feedback from SME (subject-matter-experts)
* [ ] Push to live site

### Possible solution
(Optional)
